### PR TITLE
Introduce sleep_timeout configuration + documentation

### PR DESCRIPTION
**Pull request by sti0**
This pull request introduces the sleep_timeout configuration to set a differend timeout while sleep mode is active (https://github.com/jseidl/hass-magic_areas/issues/29).

Fixes also the documentation issue (https://github.com/jseidl/hass-magic_areas/issues/27).

### CODE REVIEW

**Comment by sti0** [comment]
Overseen the dev branch. I will fix this later and push again.

**Comment by jseidl** [comment]
@sti0 thanks for the PR!

I've created a `develop` branch which contains the features I'm working on for the next release which one of them is moving constants to a separate file thus causing a conflict with your PR. 

If you have the time, could you pull the `develop` branch and apply your changes to it? I'm still to write the `CONTRIBUTORS.md` with the guidelines. If not I can perform the surgery on this PR during the week.

I'll be using [GitFlow](https://www.atlassian.com/git/tutorials/comparing-workflows/gitflow-workflow) naming for the branches (`feature/...`,`hotfix/`....) if you wanna follow along ;)

**Comment by jseidl** [comment]
> Overseen the dev branch. I will fix this later and push again.

LOL you replied while I was typing. Alright buddy thanks for the contribution!

**Comment by sti0** [comment]
> I'll be using [GitFlow](https://www.atlassian.com/git/tutorials/comparing-workflows/gitflow-workflow) naming for the branches (`feature/...`,`hotfix/`....) if you wanna follow along ;)

At work we use Bitbucket, so I'm familiar with GitFlow. I will use it next time.

@jseidl what do you think about the naming of the configuration entry? Should it be `sleep_timeout` or `sleep_clear_timeout`? In my opinion `sleep_timeout` is shorter and sounds way better but `sleep_clear_timeout` is more precise.

**Comment by sti0** [comment]
Here we go

https://github.com/jseidl/hass-magic_areas/pull/34

**Comment by jseidl** [comment]
I agree with you. `sleep_clear_timeout` is indeed more precise. Let's churn on that and decide prior to the next feature release.

Thanks for the contribution!

**Pull request closed without merging**
