### PR TITLE
Presence hold timeout

### PR DESCRIPTION
**Pull request by sti0**
Add ability to specify a `presence_hold_timeout` to reset the presence hold switch to `off` after a specified time (seconds).

This is still work in progress....
@jseidl hope that this is a suitable feature. Maybe you have some guidance for me as I'm not that digged deep in HA component development.  

ToDo:

- Mechanism to follow up the timer after restarting HA
- Update the docs

### CODE REVIEW

**Comment by jseidl** [comment]
`presence_hold` is intended to be used as a manual override. Automating it would defeat it's purpose. 

What's your use-case?

**Comment by sti0** [comment]
E.g. if I press the kitchen light switch long, the presence switch would be activated and the light stays on. Sometimes we forgot to turn off the lights by pressing the switch off. Therefore the lights stay on all the time. I like to reset the presence hold, after lets say 2 hours. At the moment I can handle this by writing a additional automation. With this option it would be possible without writing a additional automation for each of the areas. 

If you don't like to reset the presence hold switch, simply don't configurate this option.

**Comment by jseidl** [comment]
I believe you're trying to solve lack of presence measurement with presence hold. I've tried to do that in the past and it did not worked out for me. Adding more presence sensors, fiddling with the timeouts will be more beneficial in the situation where the room loses track of you from time to time (such as when cooking).

I've recently added a second motion sensor in another corner of my kitchen and my problems with the room going dark while I was reading a recipe was gone. I also have a Google assistant in the kitchen that I use as a presence sensor so when I'm cooking listening to music or watching something, that holds the presence on for me.

Can you give a try if that solves your problem?

**Comment by sti0** [comment]
We have a big living area with kitchen, dining room and living room integrated. Even it's a big room,all subareas are own areas in HA. 

if we are done with cooking and sitting down at the dining area we still like to have the kitchen lights on in a nice mood light. Therefore the presence hold is suitable because the lights stay on even if there is no presence detected. After dinner we are going outside or doing other things and the lights stay on because no one hit the light switch to turn off the lights and the presence hold switch. In such a case it would be nice to have a automatic reset of the presence hold switch.

That's only one use case and this only happens in a specific setting. Its not suitable to detect presence in one of the areas (living/dining) and turning the kitchen lights on.

**Comment by jseidl** [comment]
You could set the kitchen lights also in the Dining Area so the dining area presence would trigger the kitchen lights as well.

**Comment by sti0** [comment]
As mentioned this shouldn't happen all the time. Only at some moments. Maybe while eating or playing a cardboard game. Its not supposed to trigger kitchen light every time presence in one of the two other areas is detected. If so I simple can put all lights in one area...

**Comment by jseidl** [comment]
Gave some thought, this albeit dangerous if not used sparsely, have its uses so why not?

**Comment by jseidl** [comment]
@sti0 Updated the branch, is it ready for push to the develop branch? (I believe so but just checking)

**Comment by jseidl** [comment]
Just a 2c, use `call_later` instead of `track_time_interval`. https://dev-docs.home-assistant.io/en/master/api/helpers.html#homeassistant.helpers.event.async_call_later. I might push this fix to this branch during the weekend if you're busy!

**Comment by sti0** [comment]
@jseidl modified the code to call `call_later` now. One "issue" remains. If the timeout trigger listener is triggered and HA was restarted it doesn't continue.

There are 2 options to discuss:
1. leave it as it is - this should be a very rare problem
2. restart the listener after HA restart, if presence_hold switch is still `on` (this will extend the time, but make sure that the lights turn off somehow)

What do you think?

**Comment by jseidl** [comment]
I believe option 2 is more reliable. It doesn't quite hurt if the timer restarts and ends up taking longer. Better than not firing. Thanks for working on this!

**Comment by sti0** [comment]
@jseidl I don't forget this but been very busy these days. Had to rebase this on the new 2.x version and start rework.

**Comment by jseidl** [comment]
No worries brother, thanks for the contribution. I've been very busy as well, I feel you! 

Let me know when this is ready for review and I'll merge!

**Comment by jseidl** [comment]
I've been refactoring a lot of the code to make it compatible with PR #118 on PR #126. As part of that, I believe I'll make Presence Hold a configurable feature with it's own options page and add this functionality there instead.

**Comment by jseidl** [comment]
This is implemented on #126, thanks a lot @sti0!

**Pull request closed without merging**
