### PR TITLE
Add active_areas attribute to aggregate binary sensors of meta areas

### PR DESCRIPTION
**Pull request by caphm**
Can be used in automations to quickly get a list of which areas have active sensors without having to manually specify all areas to check/loop through.

### CODE REVIEW

**Comment by jseidl** [comment]
Thanks for the PR, I'm working on clearing the bugs identified on 2.0.x release and will start merging the new submitted features after that

**Comment by jseidl** [comment]
I believe `get_parent_area` must return a list. A single entity can reside in multiple areas with `include_entities` (I use a my external doors to trigger both the external and internal area they connect.)

**Comment by caphm** [comment]
Yes, you are right. Didn't see that use case. Newest commit contains a fix :)

**Comment by jseidl** [comment]
I've ended up changing how meta areas track their presence by tracking the other area's `binary_sensor` instead of all their sensors. This effectively makes `active_sensors` the active areas and eliminates the `get_parent_area(sensor)` logic.

I've left both `child_areas` and `active_areas` attributes but they might be redundant of `presence_sensors` and `active_sensors` now.

**Pull request merged**
