### PR TITLE
Add GitHub Actions

### PR DESCRIPTION
**Pull request by KTibow**
I recently announced ha-blueprint:
- With formatting (black + isort for python, prettier for js)
  - It’ll go ahead and pull it, format it, and amend the changes to the last commit.
- With lint
  - JS: Run ESLint to catch syntax errors
  - Python: It runs Hassfest (to catch invalid integrations), HACS (to catch invalid HACS integrations), and flake8 (to catch invalid python).

https://community.home-assistant.io/t/made-a-custom-integration-or-card-ive-created-an-all-in-one-github-action-for-you/235041
This makes it so it auto-checks for HACS, hassfest, and flake8 so you won't have to worry about it being invalid.

### CODE REVIEW

**Comment by jseidl** [comment]
This is awesome. Thanks for your contribution. Will review at night and merge!

**Comment by KTibow** [comment]
Just curious, what timezone are you on?

**Comment by jseidl** [comment]
I'm on PDT

**Comment by jseidl** [comment]
LGTM. Thanks again!

**Pull request merged**
