### PR TITLE
Advanced light controls

### PR DESCRIPTION
**Pull request by caphm**
This extends the light_groups feature and adds advanced light controls.

Lights in an area can be assigned to different categories: overhead, accent, and task lights. The light group created for the area then controls the lights depending on their category:
- Overhead lights are the main light source and will always be turned on when the group is turned on
- Accent lights are turned on when `accent_entity` is in `accent_state` (e.g. only when `sun.sun` is `below_horizon`)
- Task lights will not be turned on when the group is turned on
- When turning off the group, all contained lights are turned off, regardless of their assigned category
- Sleep lights functionality is kept the same: when `sleep_entity` is in `sleep_state`, only the defined `sleep_lights` are turned on.

All lights in the area that are not assigned to either accent or task lights will be treated as overhead lights. This way, you can either explicitly assign all light categories, or only assign accent and task lights and let all other lights be assigned implicitly.

Another option is to create sub light groups for all the light categories in the area (e.g. Kitchen Overhead Lights, Kitchen Accent Lights, Kitchen Task Lights). I like to use those because I'm rarely ever turning on/off individual lights, but rather an entire category at once. This is optional however.

The behaviour if there are already some lights in the group turned on is as follows (in the order listed):
- If there are parameters given to the call to the turn_on service, the group will only act on the lights that are already turned on. This allows to change brightness, color and other attributes of turned on lights without turning on additional lights.
- If the area is in sleep mode, sleep lights are turned on
- If there are no overhead lights on (e.g. only accent or task lights), the overhead lights are turned on. This allows you to turn on the overhead lights when only your desk lamp is on without having to specifically specify it.

You can checkout a detailed behaviour chart here: https://docs.google.com/spreadsheets/d/106aUjxl3eox7chds_P7xT2Tiu7t7UltkIwGIKMoi0QI/edit?usp=sharing

Additionally, accent lights are turned on automatically once `accent_entity` changes to `accent_state`.

To disable all this functionality, just don't assign any accent or task lights, and everything will work just like before.

A more technical change: The autolights feature is now handled by the light group. That's why a light group is also created when the `control_lights` feature is enabled. The AreaPresenceBinarySensor fires a signal when its state changes to on or off and the light group reacts to this, if the `control_lights` feature is enabled and `night_entity` is not in `night_state`.

### CODE REVIEW

**Comment by jseidl** [comment]
Hey, thanks for the work on that. Been really busy at work, will need some time to go through this PR.

**Comment by jseidl** [comment]
Hi sorry it took so long to get back at you. First of all, thanks for that huge work you did and I love it!

I really like of the idea of delegating light control to the light groups through eventing. I was looking into removing the control logic from the area binary sensor for a while now and that's a really nice way of accomplishing it.

I believe this can be further expanded to control_media and control_climate, create instead climate groups and media groups and use it to control those.

One problem I see is that the amount of configuration options is already too much for a single config_flow step, need to come with a new config_flow step just for the light group options (actually, start breaking down those big-feature options into their own config_flow steps).

I still feel that light control should be according to an area's state (dark, sleep etc). Maybe we can find a better state name for the accent lights rather than `is_accenting`?

Again, thanks a lot for this. All great ideas but since they'll break stuff, I'll schedule this for `3.0.0`. In the meantime I can work on the other groups (media, climate) and migrating the controls into there through eventing/signaling. Also the config_flow stuff should be there for `3.0.0` as well.

**Comment by caphm** [comment]
Hey, didn't check my notifications, so now we're even with taking some time to getting back to each other ;)

I'm happy to collaborate with you on including several features in `3.0.0` if you'd like. There are some other feature requests (like #106) that I'm personally very interested in.

> I believe this can be further expanded to control_media and control_climate, create instead climate groups and media groups and use it to control those.

I did think so too. Can be especially useful with climate groups for example turning off the heating when a window in the area opens.

> One problem I see is that the amount of configuration options is already too much for a single config_flow step, need to come with a new config_flow step just for the light group options (actually, start breaking down those big-feature options into their own config_flow steps).

Definitely with you on that. I didn't want to introduce too many changes at once though. Maybe its most sensible to have an initial config flow step where the user selects the features for the area and can dial in some general settings, and then have individual config_flow steps for all the features that are enabled.

I'm not quite sure on how to go about this though... I guess it's best to include the separation into multiple config_flow steps in the base branch, then backport these changes into this PR and build on top of that. If I include it here, this PR becomes a catch-all for different types of changes, which makes it harder to manage...

> I still feel that light control should be according to an area's state (dark, sleep etc). Maybe we can find a better state name for the accent lights rather than `is_accenting`?

I cringed at that naming as well, but hey, it works :)

**Comment by jseidl** [comment]
Awesome, thanks for the work on that! This weekend I shall have a bit more time to go over this

**Comment by jseidl** [comment]
I think I've came to something. The idea is to have a `states` list on the area object. Trackers for entities for `dark` and `sleep` update this list and fire a `AREA_STATE_CHANGED` event. Rest of stuff can listen to that event and call `in_state('sleep')` to see if they need to run.

This way `accent` can be a state of the area. It's basically the same thing but having all states in a list which we can probe.

My idea for this is to enable other meta-state changes like `prolonged` after the room has been occupied for a set amount of time. This would enable climate to listen to this state and only then turn on, to avoid fans coming up when you're just entering a room to pick up something.

Regarding:

> Another option is to create sub light groups for all the light categories in the area (e.g. Kitchen Overhead Lights, Kitchen Accent Lights, Kitchen Task Lights). 

I really like this too. Seems that is currently not the way this PR is doing this. Is that correct? (Just to know if it's something to track as I also prefer to have the individual groups for the same reasons).

Finally merged the other PRs and I'm doing some fixes. Shall be releasing a minor version with those and start preparing this PR's changes for 3.0.

**Comment by jseidl** [comment]
This is implemented (mostly) on #126. If there's a gap lets work on it after `3.0.0` release. Thanks a lot @caphm!

**Pull request closed without merging**
